site_name: Jetstar Virtual Standard Operating Procedures
repo_url: https://github.com/jqvirtual/jqv-sops
repo_name: jqvirtual/jqv-sops
extra_css:
    - stylesheets/navigation.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
theme:
  name: material
  logo: img/jq.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.tooltips